version: "3.9"
services:

  # Postgres
  postgres:
    image: postgres
    restart: always
    volumes:
      # Data storage
      - type: bind
        source: volumes/data
        target: /var/lib/postgresql/data
      # Secrets (passwords etc.)
      - type: bind
        source: volumes/secrets
        target: /run/secrets
      # Initialisation scripts (only run if data volume is empty)
      - type: bind
        source: volumes/init
        target: /docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
      - POSTGRES_HOST=postgres
    ports:
      - "5432:5432"

  migrate:
    build: .
    depends_on:
      - postgres
    volumes:
      # Secrets (passwords etc.)
      - type: bind
        source: volumes/secrets
        target: /run/secrets
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-passwd
    command: /out/migrate --path /migrations

  auth:
    build: .
    ports:
      - "8000:8080"
    depends_on:
      - migrate
      - postgres
    command: /out/auth