version: "3.9"
services:
  memcached1:
    image: memcached:latest
    ports:
        - 11212:11211
  memcached2:
    image: memcached:latest
    ports:
        - 11213:11211
  mcrouter:
    image: docker-registry.wikimedia.org/mcrouter:latest
    platform: linux/amd64
    links:
        - memcached1:memcached1
        - memcached2:memcached2
    command: mcrouter --config-str='{"pools":{"sharded":{"servers":["memcached1:11211","memcached2:11211"]}},"route":{"type":"LoadBalancerRoute","children":"Pool|sharded"}}' -p 11211
    ports:
        - 11211:11211
