.PHONY: run
run:
	docker-compose up -d

# .PHONY: publisher
# publisher:
# 	go run ./producer/ --brokerList=localhost:9092 --topicPrefix=jobs --cronPath=cron.yaml

# .PHONY: consumer-a
# consumer-a:
# 	go run ./consumer/ --brokerList=localhost:9092 --topic=jobs-cluster-a

# .PHONY: consumer-b
# consumer-b:
# 	go run ./consumer/ --brokerList=localhost:9092 --topic=jobs-cluster-b