baseURL = "http://example.org/"
languageCode = "en-us"
title = "CYF+"
languageLang = "en"
sectionPagesMenu = "main"
enableGitInfo = true

[params]
description = "A free and open source immersive engineering programme. Practical, hands on projects in Go, distributed systems engineering, site reliability engineering, software engineering. Pace, scale, and complexity."
tree = "https://github.com/CodeYourFuture/immersive-go-course/tree/main/"

[frontmatter]
lastmod = [":git", "date", "publishDate"]

[markup]
[markup.tableOfContents]
endLevel = 5
ordered = true
startLevel = 2
[markup.highlight]
lineNos = false
codeFences = true
guessSyntax = true

disableKinds = ["RSS", "taxonomy", "taxonomyTerm", "categories"]
