baseURL = "/"
languageCode = "en-us"
title = "CYF+"
languageLang = "en"

[params]
description = "A free and open source immersive engineering programme. Practical, hands on projects in Go, distributed systems engineering, site reliability engineering, software engineering. Pace, scale, and complexity."
repo = "https://github.com/CodeYourFuture/immersive-go-course/"
tree = "https://github.com/CodeYourFuture/immersive-go-course/tree/main/"
edit = "https://github.com/CodeYourFuture/immersive-go-course/edit/main/"

[markup]
[markup.tableOfContents]
endLevel = 6
ordered = true
startLevel = 2
[markup.highlight]
lineNos = false
codeFences = true
guessSyntax = true
[markup.goldmark.renderer]
# Enable HTML codeblocks, e.g. for <details> blocks
unsafe = true

disableKinds = ["taxonomy", "term"]
[taxonomies]
series = "versions"
