[build]
publish = "public"
command = "node index.js && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "0.109.0"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[context.deploy-preview]
command = "hugo --gc --minify --buildFuture -b $DEPLOY_PRIME_URL"
