apiVersion: v1
kind: ConfigMap
metadata:
  name: amconfig
data:
  # file-like keys
  alertmanager.conf: |
    # Minimal alertmanager config that doesn't send alerts anywhere - 
    # Visible at http://localhost:9093/#/alerts
    global:
      resolve_timeout: 5m
    route:
      receiver: "null"
      group_by:
      - job
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 12h
    receivers:
      - name: "null"