name: Docker cloud tests and deploy
on: [push]
defaults:
  run:
    working-directory: docker-cloud
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: "docker-cloud/go.mod"
          cache-dependency-path: docker-cloud/go.sum
          cache: true

      - name: Build
        run: docker build -t docker-cloud:latest

      - name: Test
        run: go test -v ./...
